-- --------------------------------------------------------
-- Host:                         127.0.0.2
-- Server version:               8.0.26 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for coep
CREATE DATABASE IF NOT EXISTS `coep` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `coep`;

-- Dumping structure for table coep.studentperformance
CREATE TABLE IF NOT EXISTS `studentperformance` (
  `SID` int DEFAULT NULL,
  `question_paper_id` int DEFAULT NULL,
  `topicnumber` int DEFAULT NULL,
  `variation` int DEFAULT NULL,
  `DOD` int DEFAULT NULL,
  `question` varchar(1000) DEFAULT NULL,
  `coption` varchar(1000) DEFAULT NULL,
  `woption1` varchar(1000) DEFAULT NULL,
  `woption2` varchar(1000) DEFAULT NULL,
  `woption3` varchar(1000) DEFAULT NULL,
  `solution` varchar(1000) DEFAULT NULL,
  `answer` int DEFAULT NULL,
  `timetaken` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table coep.studentperformance: ~16 rows (approximately)
/*!40000 ALTER TABLE `studentperformance` DISABLE KEYS */;
INSERT INTO `studentperformance` (`SID`, `question_paper_id`, `topicnumber`, `variation`, `DOD`, `question`, `coption`, `woption1`, `woption2`, `woption3`, `solution`, `answer`, `timetaken`) VALUES
	(1, 1, 30102, 1, 1, 'Following two expressions  $6 \\times 3$ and $15 + 3$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $6 \\times 3$ आणि  $15 + 3$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 6 \\times 3 = 18 $ and $ 15 + 3 = 18 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$6 \\times 3 = 15 + 3$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 6 \\times 3 = 18 $ आणि $ 15 + 3 = 18 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$6 \\times 3 = 15 + 3$', 1, 55),
	(1, 1, 30102, 1, 1, 'Following two expressions  $2 \\times 4$ and $19 - 11$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $2 \\times 4$ आणि  $19 - 11$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 2 \\times 4 = 8 $ and $ 19 - 11 = 8 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$2 \\times 4 = 19 - 11$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 2 \\times 4 = 8 $ आणि $ 19 - 11 = 8 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$2 \\times 4 = 19 - 11$', 0, 55),
	(1, 1, 30102, 1, 1, 'Following two expressions  $6 \\times 3$ and $15 + 3$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $6 \\times 3$ आणि  $15 + 3$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 6 \\times 3 = 18 $ and $ 15 + 3 = 18 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$6 \\times 3 = 15 + 3$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 6 \\times 3 = 18 $ आणि $ 15 + 3 = 18 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$6 \\times 3 = 15 + 3$', 1, 54),
	(1, 1, 30102, 1, 1, 'Following two expressions  $11 - 5$ and $1 \\times 6$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $11 - 5$ आणि  $1 \\times 6$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 11 - 5 = 6 $ and $ 1 \\times 6 = 6 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$11 - 5 = 1 \\times 6$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 11 - 5 = 6 $ आणि $ 1 \\times 6 = 6 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$11 - 5 = 1 \\times 6$', 1, 56),
	(1, 1, 30102, 2, 2, 'Following two expressions  $9 - 1$ and $9 \\times 1$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $9 - 1$ आणि  $9 \\times 1$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'False <br> # चूक', 'True <br> # बरोबर', '', '', 'Answer - False <br>In mathematics we can equate any two expressions if the values of both sides of the expressions are equal.<br>Here, $ 9 - 1 = 8 $ and $ 9 \\times 1 = 9 $<br>Since both these expressions are not giving same value we can not equate these two, to form an equation.<br>$9 - 1 ≠ 9 \\times 1$<br> # उत्तर - चूक <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हाच ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 9 - 1 = 8 $ आणि $ 9 \\times 1 = 9 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान नाही. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येणार नाहीत.<br>$9 - 1 ≠ 9 \\times 1$', 0, 53),
	(1, 1, 30102, 2, 2, 'Following two expressions  $5 \\times 6$ and $11 + 6$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $5 \\times 6$ आणि  $11 + 6$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'False <br> # चूक', 'True <br> # बरोबर', '', '', 'Answer - False <br>In mathematics we can equate any two expressions if the values of both sides of the expressions are equal.<br>Here, $ 5 \\times 6 = 30 $ and $ 11 + 6 = 17 $<br>Since both these expressions are not giving same value we can not equate these two, to form an equation.<br>$5 \\times 6 ≠ 11 + 6$<br> # उत्तर - चूक <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हाच ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 5 \\times 6 = 30 $ आणि $ 11 + 6 = 17 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान नाही. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येणार नाहीत.<br>$5 \\times 6 ≠ 11 + 6$', 1, 55),
	(1, 1, 30102, 2, 2, 'Following two expressions  $8 + 16$ and $5 - 20$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $8 + 16$ आणि  $5 - 20$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'False <br> # चूक', 'True <br> # बरोबर', '', '', 'Answer - False <br>In mathematics we can equate any two expressions if the values of both sides of the expressions are equal.<br>Here, $ 8 + 16 = 24 $ and $ 5 - 20 = -15 $<br>Since both these expressions are not giving same value we can not equate these two, to form an equation.<br>$8 + 16 ≠ 5 - 20$<br> # उत्तर - चूक <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हाच ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 8 + 16 = 24 $ आणि $ 5 - 20 = -15 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान नाही. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येणार नाहीत.<br>$8 + 16 ≠ 5 - 20$', 1, 58),
	(1, 1, 30102, 110, 3, 'Match the pairs for equality / समीकरण तयार होतील अशा योग्य जोड्या जुळवा <br>\\[\n            \\begin{array}{|c|c|c|c|}\n            \\hline\n            \\text{ } & \\text{A}& \\text{ } & \\text{B} \\\\\n            \\hline\n            1 & 86\\ \\times\\ 49 & a. & 87\\ -\\ 12 \\\\\n            \\hline\n            2 & 33\\ \\times\\ 98 & b. & 77\\ \\times\\ 42 \\\\\n            \\hline\n            3 & 13\\ +\\ 62 & c. & 98\\ \\times\\ 43 \\\\\n            \\hline\n            4 & 28\\ +\\ 71 & d. & 56\\ +\\ 43 \\\\\n            \\hline\n            \\end{array}\n            \\]\n        ', '$1-c,2-b,3-a,4-d$', '$1-b,2-c,3-a,4-d$', '$1-c,2-a,3-b,4-d$', '$1-c,2-b,3-d,4-a$', 'Answer/उत्तर: $$1-c,2-b,3-a,4-d$$ <br> 1. By solving $A$ and $B$ we get / $A$ आणि $B$ सोडवून <br>\\[\n            \\begin{array}{|c|c|c|c|}\n            \\hline\n            \\text{ } & \\text{A}& \\text{ } & \\text{B} \\\\\n            \\hline\n            1 & 86\\ \\times\\ 49 = 4214 & c. & 98\\ \\times\\ 43 = 4214 \\\\\n            \\hline\n            2 & 33\\ \\times\\ 98 = 3234 & b. & 77\\ \\times\\ 42 = 3234 \\\\\n            \\hline\n            3 & 13\\ +\\ 62 = 75 & a. & 87\\ -\\ 12 = 75 \\\\\n            \\hline\n            4 & 28\\ +\\ 71 = 99 & d. & 56\\ +\\ 43 = 99 \\\\\n            \\hline\n            \\end{array}\n            \\]<br>From this, correct pairing which can form equation are $$1-c,2-b,3-a,4-d$$<br>या वरून योग्य जोड्या $$1-c,2-b,3-a,4-d$$ आहेत.\n            ', 0, 54),
	(1, 1, 30102, 108, 3, 'Coffee Shop is $700$ metres from Factory. Medicine Shop is $950$ metres from Office. Which of the following statement is correct?<br>#कॉफी शॉप आणि कारखाना यातील अंतर $700$ मी आहे. तर औषधाचे दुकान आणि कार्यालय यातील अंतर $950$ मी आहे. तर खालील पैकी कोणते विधान बरोबर आहे?', 'Distance between Coffee Shop and Factory is not equal to distance between Medicine Shop and Office<br>#कॉफी शॉप ते कारखाना यातील अंतर आणि औषधाचे दुकान ते कार्यालय यातील अंतर समान नाही', 'Distance between Coffee Shop and Medicine Shop is same as distance between Factory and Office<br>#कॉफी शॉप ते औषधाचे दुकान यातील अंतर आणि कारखाना ते कार्यालय यातील अंतर समान आहे', 'Distance between Coffee Shop and Office is same as distance between Medicine Shop and Office<br>#कॉफी शॉप ते कार्यालय यातील अंतर आणि औषधाचे दुकान ते कार्यालय यातील अंतर समान आहे', 'Distance between Coffee Shop and Factory is equal to distance between Medicine Shop and Office<br>#कॉफी शॉप ते कारखाना यातील अंतर आणि औषधाचे दुकान ते कार्यालय यातील अंतर समान आहे', 'Answer: Distance between Coffee Shop and Factory is not equal to distance between Medicine Shop and Office <br> Distance between Coffee Shop and Factory = $700\\ m$<br> Distance between Medicine Shop and Office = $950\\ m$<br> Other distances mentioned in options are not known and can\'t be found out. $\\therefore$ distances given in statement are not equal.<br># उत्तर: कॉफी शॉप ते कारखाना यातील अंतर आणि औषधाचे दुकान ते कार्यालय यातील अंतर समान नाही <br> कॉफी शॉप ते कारखाना यातील अंतर = $700$ मी आहे.<br> औषधाचे दुकान ते कार्यालय यातील अंतर = $950$ मी आहे. <br> पर्यायामध्ये उल्लेख केलेली अंतरे माहिती नहित आणि ठरवता पण येत नाहीत. म्हणून विधानात विचारलेली अंतरे समान नाहीत. <br>', 1, 56),
	(1, 2, 30102, 1, 1, 'Following two expressions  $10 + 10$ and $20 - 0$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $10 + 10$ आणि  $20 - 0$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 10 + 10 = 20 $ and $ 20 - 0 = 20 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$10 + 10 = 20 - 0$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 10 + 10 = 20 $ आणि $ 20 - 0 = 20 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$10 + 10 = 20 - 0$', NULL, NULL),
	(1, 2, 30102, 1, 1, 'Following two expressions  $5 \\times 4$ and $18 + 2$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $5 \\times 4$ आणि  $18 + 2$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'True <br> # बरोबर', 'False <br> # चूक', '', '', 'Answer - True<br>In mathematics we can equate any two expressions if the values of both sides of expressions are equal.<br>Here, $ 5 \\times 4 = 20 $ and $ 18 + 2 = 20 $<br>Since both the given expressions are giving the same value we can equate these two to form an equation.<br>$5 \\times 4 = 18 + 2$<br> # उत्तर - बरोबर <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हा ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 5 \\times 4 = 20 $ आणि $ 18 + 2 = 20 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान आहे. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येतील.<br>$5 \\times 4 = 18 + 2$', NULL, NULL),
	(1, 2, 30102, 2, 2, 'Following two expressions  $3 \\times 8$ and $8 + 23$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $3 \\times 8$ आणि  $8 + 23$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'False <br> # चूक', 'True <br> # बरोबर', '', '', 'Answer - False <br>In mathematics we can equate any two expressions if the values of both sides of the expressions are equal.<br>Here, $ 3 \\times 8 = 24 $ and $ 8 + 23 = 31 $<br>Since both these expressions are not giving same value we can not equate these two, to form an equation.<br>$3 \\times 8 ≠ 8 + 23$<br> # उत्तर - चूक <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हाच ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 3 \\times 8 = 24 $ आणि $ 8 + 23 = 31 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान नाही. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येणार नाहीत.<br>$3 \\times 8 ≠ 8 + 23$', NULL, NULL),
	(1, 2, 30102, 2, 2, 'Following two expressions  $3 \\times 6$ and $20 - 13$ will form two sides (LHS and RHS) of an equation. <br> # खाली दिलेली दोन विधाने  $3 \\times 6$ आणि  $20 - 13$ मिळून समीकरण (डावी बाजू = उजवी बाजू) बनवू शकतात.', 'False <br> # चूक', 'True <br> # बरोबर', '', '', 'Answer - False <br>In mathematics we can equate any two expressions if the values of both sides of the expressions are equal.<br>Here, $ 3 \\times 6 = 18 $ and $ 20 - 13 = 7 $<br>Since both these expressions are not giving same value we can not equate these two, to form an equation.<br>$3 \\times 6 ≠ 20 - 13$<br> # उत्तर - चूक <br>जेंव्हा दोन गणिती विधानांचे मूल्य समान असते तेव्हाच ती दोन विधाने समीकरण पध्दतीने मांडता येतात.<br>$ 3 \\times 6 = 18 $ आणि $ 20 - 13 = 7 $ <br>येथे दिलेल्या दोन्ही गणिती विधानांचे मूल्य समान नाही. त्यामुळे दिलेली दोन्ही विधाने मिळून समीकरण पध्दतीने मांडता येणार नाहीत.<br>$3 \\times 6 ≠ 20 - 13$', NULL, NULL),
	(1, 2, 30102, 106, 3, 'Library is $850$ metres from Supermarket. Coffee Shop is $250$ metres from Supermarket. Assuming Library and Coffee Shop are in the opposite direction from Supermarket which of the following statement is correct?<br>#ग्रंथालय आणि सुपरमार्केट यातील अंतर $850$  मी आहे. सुपरमार्केट पासून कॉफी शॉप $250$ मी अंतरावर आहे. कॉफी शॉप आणि ग्रंथालय हे दोन्ही सुपरमार्केट पासून एकमेकांच्या विरुद्ध दिशेला आहेत. तर खालील पैकी कोणते विधान बरोबर आहे?', 'Supermarket is not at equal distance from Coffee Shop and Library both<br>#सुपरमार्केट हे कॉफी शॉप आणि ग्रंथालय या पासून समान अंतरावर नाही', 'Supermarket is at equal distance from Library and Coffee Shop both<br>#सुपरमार्केट हे ग्रंथालय आणि कॉफी शॉप या पासून समान अंतरावर आहे', 'Distance between Supermarket and Library and distance between Coffee Shop and Library is equal<br>#ग्रंथालय आणि सुपरमार्केट, तसेच ग्रंथालय आणि कॉफी शॉप यातील अंतर समान आहे', 'Distance between Coffee Shop and Supermarket and distance between Coffee Shop and Library is equal<br>#कॉफी शॉप आणि सुपरमार्केट, तसेच कॉफी शॉप आणि ग्रंथालय यातील अंतर समान आहे', 'Answer: Supermarket is not at equal distance from Coffee Shop and Library both <br> Distance between Supermarket and Library = $850\\ m$<br>Distance between Supermarket and Coffee Shop = $250\\ m$<br>$\\therefore$ Distance of Supermarket from Library and Coffee Shop is not equal <br># उत्तर: सुपरमार्केट हे कॉफी शॉप आणि ग्रंथालय या पासून समान अंतरावर नाही <br> सुपरमार्केट आणि ग्रंथालय मधील अंतर = $850$ मी<br> सुपरमार्केट आणि कॉफी शॉप मधील अंतर = $250$ मी<br>$\\therefore$ सुपरमार्केट हे ग्रंथालय आणि कॉफी शॉप या पासून समान अंतरावर नाही.', NULL, NULL),
	(1, 2, 30102, 106, 3, 'Hospital is $200$ metres from Salon. Grocery Shop is $250$ metres from Salon. Assuming Hospital and Grocery Shop are in the opposite direction from Salon which of the following statement is correct?<br>#रुग्णालय आणि सलून यातील अंतर $200$  मी आहे. सलून पासून किराणा मालाचे दुकान $250$ मी अंतरावर आहे. किराणा मालाचे दुकान आणि रुग्णालय हे दोन्ही सलून पासून एकमेकांच्या विरुद्ध दिशेला आहेत. तर खालील पैकी कोणते विधान बरोबर आहे?', 'Salon is not at equal distance from Grocery Shop and Hospital both<br>#सलून हे किराणा मालाचे दुकान आणि रुग्णालय या पासून समान अंतरावर नाही', 'Distance between Salon and Hospital and distance between Grocery Shop and Hospital is equal<br>#रुग्णालय आणि सलून, तसेच रुग्णालय आणि किराणा मालाचे दुकान यातील अंतर समान आहे', 'Distance between Grocery Shop and Salon and distance between Grocery Shop and Hospital is equal<br>#किराणा मालाचे दुकान आणि सलून, तसेच किराणा मालाचे दुकान आणि रुग्णालय यातील अंतर समान आहे', 'Salon is at equal distance from Hospital and Grocery Shop both<br>#सलून हे रुग्णालय आणि किराणा मालाचे दुकान या पासून समान अंतरावर आहे', 'Answer: Salon is not at equal distance from Grocery Shop and Hospital both <br> Distance between Salon and Hospital = $200\\ m$<br>Distance between Salon and Grocery Shop = $250\\ m$<br>$\\therefore$ Distance of Salon from Hospital and Grocery Shop is not equal <br># उत्तर: सलून हे किराणा मालाचे दुकान आणि रुग्णालय या पासून समान अंतरावर नाही <br> सलून आणि रुग्णालय मधील अंतर = $200$ मी<br> सलून आणि किराणा मालाचे दुकान मधील अंतर = $250$ मी<br>$\\therefore$ सलून हे रुग्णालय आणि किराणा मालाचे दुकान या पासून समान अंतरावर नाही.', NULL, NULL),
	(1, 2, 30102, 110, 3, 'Match the pairs for equality / समीकरण तयार होतील अशा योग्य जोड्या जुळवा <br>\\[\n            \\begin{array}{|c|c|c|c|}\n            \\hline\n            \\text{ } & \\text{A}& \\text{ } & \\text{B} \\\\\n            \\hline\n            1 & 83\\ \\times\\ 13 & a. & 68\\ \\div\\ 72 \\\\\n            \\hline\n            2 & 59\\ \\div\\ 68 & b. & 65\\ \\div\\ 75 \\\\\n            \\hline\n            3 & 47\\ \\times\\ 35 & c. & 35\\ \\times\\ 47 \\\\\n            \\hline\n            4 & 48\\ \\div\\ 51 & d. & 13\\ \\times\\ 83 \\\\\n            \\hline\n            \\end{array}\n            \\]\n        ', '$1-d,2-b,3-c,4-a$', '$1-d,2-b,3-a,4-c$', '$1-a,2-b,3-c,4-d$', '$1-c,2-b,3-d,4-a$', 'Answer/उत्तर: $$1-d,2-b,3-c,4-a$$ <br> 1. By solving $A$ and $B$ we get / $A$ आणि $B$ सोडवून <br>\\[\n            \\begin{array}{|c|c|c|c|}\n            \\hline\n            \\text{ } & \\text{A}& \\text{ } & \\text{B} \\\\\n            \\hline\n            1 & 83\\ \\times\\ 13 = 1079 & d. & 13\\ \\times\\ 83 = 1079 \\\\\n            \\hline\n            2 & 59\\ \\div\\ 68 = 0.87 & b. & 65\\ \\div\\ 75 = 0.87 \\\\\n            \\hline\n            3 & 47\\ \\times\\ 35 = 1645 & c. & 35\\ \\times\\ 47 = 1645 \\\\\n            \\hline\n            4 & 48\\ \\div\\ 51 = 0.94 & a. & 68\\ \\div\\ 72 = 0.94 \\\\\n            \\hline\n            \\end{array}\n            \\]<br>From this, correct pairing which can form equation are $$1-d,2-b,3-c,4-a$$<br>या वरून योग्य जोड्या $$1-d,2-b,3-c,4-a$$ आहेत.\n            ', NULL, NULL);
/*!40000 ALTER TABLE `studentperformance` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
